[package]
name = "track2line"
version = "0.7.0"
edition = "2024"

[dependencies]
track2line_lib = { git = "https://github.com/Uliboooo/track2line_lib", tag = "0.2.0" }
get_input = { git = "https://github.com/Uliboooo/get_input", tag = "0.5.0" }
clap = { version = "4.5.31", features = ["derive"] }
serde = { version = "1.0.218", features = ["derive"] }
toml = "0.8.20"
home = "0.5.11"
